### ISSUE TITLE
Failed to build on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by sandakersmann** [sigp/lighthouse#2939]
Failed to build v2.1.0 on Ubuntu 20.04.3 LTS. Got this error message:

```
   Compiling tree_hash_derive v0.4.0
   Compiling tree_hash_derive v0.4.0 (/home/ethereum/git/lighthouse/consensus/tree_hash_derive)
error: failed to run custom build command for `mdbx-sys v0.11.4-git.20210105`

Caused by:
  process didn't exit successfully: `/home/ethereum/git/lighthouse/target/release/build/mdbx-sys-f990432a27008d6b/build-script-build` (exit status: 101)
  --- stderr
  /home/ethereum/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbx-sys-0.11.4-git.20210105/libmdbx/mdbx.h:172:10: fatal error: 'stdarg.h' file not found
  /home/ethereum/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbx-sys-0.11.4-git.20210105/libmdbx/mdbx.h:172:10: fatal error: 'stdarg.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate bindings: ()', /home/ethereum/.cargo/registry/src/github.com-1ecc6299db9ec823/mdbx-sys-0.11.4-git.20210105/build.rs:71:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `lighthouse v2.1.0 (/home/ethereum/git/lighthouse/lighthouse)`, intermediate artifacts can be found at `/home/ethereum/git/lighthouse/target`

Caused by:
  build failed
make: *** [Makefile:28: install] Error 101
```

**Comment by pawanjay176** [comment]
Lighthouse now requires `libclang` when building from source. I think an `apt install` should fix this
```
sudo apt install libclang-dev clang
```

**Comment by sandakersmann** [comment]
Yes. That fixed the issue. Thanks :)

**Comment by FabianSchuessler** [comment]
I had the same issue. I think this should be mentioned in the release notes.
