### PR TITLE
Fix compilation error on eip4844 branch

### PR DESCRIPTION
**Pull request by jimmygchen**
## Issue Addressed

Fix incorrect return value causing compilation to fail.

Note: I also had to upgrade my local rustc to 1.65 to get rid of the [GAT](https://blog.rust-lang.org/2022/10/28/gats-stabilization.html) errors. @michaelsproul confirmed the plan is to upgrade Minimum Supported Rust Version (MSRV) to 1.65 soon.

### CODE REVIEW

**Comment by jimmygchen** [comment]
This branch now builds on my machine with rustc 1.65 installed

**Comment by realbigsean** [comment]
Awesome, thanks!
