### ISSUE TITLE
[Build Error] Lighthouse v0.1.0 fails to build on OSX

### ISSUE THREAD

**Issue by djrtwo** [sigp/lighthouse#689]
## Description

Lighthouse v0.1.0 fails to build on macOS 10.13.2.

## Present Behaviour

Did a fresh pull of lighthouse v0.1.0 and ran `make` (attempted a couple of times with same result)

Below is the failing snippet of output:

```
   Compiling websocket_server v0.1.0 (/Users/djrtwo/dev/ethereum/lighthouse/beacon_node/websocket_server)
   Compiling environment v0.1.0 (/Users/djrtwo/dev/ethereum/lighthouse/lighthouse/environment)
error[E0008]: cannot bind by-move into a pattern guard
   --> beacon_node/eth2-libp2p/src/rpc/handler.rs:259:35
    |
259 |             RPCEvent::Request(id, request) if request.expect_response() => {
    |                                   ^^^^^^^ moves value into pattern guard

error[E0008]: cannot bind by-move into a pattern guard
   --> beacon_node/eth2-libp2p/src/rpc/handler.rs:305:74
    |
305 |                             InboundSubstreamState::ResponsePendingSend { substream, closing }
    |                                                                          ^^^^^^^^^ moves value into pattern guard

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0008`.
error: Could not compile `eth2-libp2p`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `lighthouse v0.1.0 (/Users/djrtwo/dev/ethereum/lighthouse/lighthouse)`, intermediate artifacts can be found at `/Users/djrtwo/dev/ethereum/lighthouse/target`

Caused by:
  build failed
make: *** [install] Error 101
```

## Expected Behaviour

It should build!

Note that this is an out-dated version of macOS. You can just tell me that you don't support v10.13 if you don't :)

**Comment by pawanjay176** [comment]
Can you try building after running `rustup update` ? I think this might be a new feature in Rust 1.39 which was released recently.

**Comment by djrtwo** [comment]
Yup, that did it. Thanks!
