### ISSUE TITLE
Lighthouse v1.4.0 does not compile with latest Rust (1.53.0+)

### ISSUE THREAD

**Issue by piotrbednarczyk** [sigp/lighthouse#2420]
## Description

Compilation error during lighthouse v1.4.0 compilation:

Compiling lighthouse v1.4.0 (/home/lighthouse/lighthouse)
error[E0275]: overflow evaluating the requirement `(PhantomData<warp::filter::or::Or<warp::filter::or::Or<warp::filter::or::Or<warp::filter::or::Or<warp::filter::or::Or<warp::filter::or::Or<warp::filter$

Full error log in attachment. [error.log](https://github.com/sigp/lighthouse/files/6721785/error.log)

## Version

git log:
commit 3b600acdc5bf9726367c18277a22486573b8b457 (HEAD -> stable, tag: v1.4.0, origin/stable)

rustc --version --verbose:
rustc 1.53.0 (53cb7b09b 2021-06-17)
binary: rustc
commit-hash: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
commit-date: 2021-06-17
host: x86_64-unknown-linux-gnu
release: 1.53.0
LLVM version: 12.0.1

hostnamectl:
Virtualization: kvm
Operating System: Ubuntu 18.04.5 LTS
Kernel: Linux 4.15.0-123-generic
Architecture: x86-64

**Comment by kasper0406** [comment]
I hit the same issue with the following version of rust:
```
stable-aarch64-unknown-linux-gnu
rustc 1.53.0 (53cb7b09b 2021-06-17)
```
Downgrading to rust 1.52.0 using `rustup default 1.52.0` made it compile for me.

**Comment by michaelsproul** [comment]
Unfortunately this breakage was out of our control due to a breaking release of the Rust compiler which occurred after Lighthouse v1.4.0 was released. Compatibility with Rust 1.53.0 will be restored in the next Lighthouse release.

For reference, here's the Discord announcement that was made: https://discord.com/channels/605577013327167508/711866597308104745/857047793489936405

And the instructions for downgrading:

```sh
cd lighthouse
rustup toolchain install 1.52.1
rustup override set 1.52.1
make
```

NB: Downgrading to 1.52.1 rather than 1.52.0 is recommended, as [Rust 1.52.0 contains a bug](https://blog.rust-lang.org/2021/05/10/Rust-1.52.1.html).
